### ISSUE TITLE
Edit Menu - Paste New

### ISSUE THREAD

**Issue by rachelkg** [IDEMSInternational/R-Instat#8815] opened 2024-02-14 19:13 UTC
Hello @rdstern and @N-thony, 

I the edit menu there is an item called Paste New. This takes the data from the clipboard and makes it into its own data frame. Should this menu item be called Paste New Data Frame? I think it would be clearer, Paste new feels a bit ambiguous. 

![2024-02-14_11-10-28](https://github.com/IDEMSInternational/R-Instat/assets/85707390/7232d679-0103-4cef-a3f7-7f25fe381329)

**Comment by rdstern** [comment] 2024-02-15 11:42
@Fidel365 Here are Rachel's questions, to answer, so she can write the help for this dialog.  I hope you can help her.  You may have to check with Patrick if there are bits you can't answer.  There may not be any code changes needed, in which case you can continue the discussion here.  Then @rachelkg can close this issue when she has the information needed:

She writes:
"In the paste to new dataframe help you immediately give an example that doesnt work. I suggest we start by outlining when this does work. i see that it works well with data from other data frames and from excel. Would it work well coming in from other stats programs? 

I assume the disadvantage is that it doesn't bring any of the column metadata so we recommend importing? 

How about the columns feature? What are the parameters for this? I have tried some but keep getting errors. I guess because I am trying to add my data to data frames that do not match it in some way? Maybe good to have a quick chat about it tomorrow if you have time. "

My answer so far.  When you open this dialog it simply copies whatever text is in the clipboard.  So, in the current help we could assume the Edit > Copy New Data Frame dialog is open and the Help has been clicked.  Now they could go down to the data shown (the 4 rows).  They could mark the 4 rows, then either right-click and choose Copy, or press <ctrl>C, which is the same thing.
Now close the help and lo and behold, nothing has happened!  But click on the Reset button and the text copies into the dialog.  Then untick the option to use the first row as the header.  Then you are ready to go!

It can be very quick and convenient to copy data into R-Instat in this way.  But it is only for small datasets, because it is limited to the visible window onto the data.  Usually it is just for a few rows and columns.  So, from Excel, etc, you usually us the File > Import from mFime dialog.

You can also add these data to an existing data frame, that's the Columns option, but here there are some restrictions.  Perhaps, in the Help that might be an Anchor point? Usually what you copy will be the same length as the data frame.  So you could add another opy of the same data.

Otherwise you could open the usual survey data and copy the column to there.  It will repeat going down - rarely what you want!  Or you could make a new data frame as shown in the File > New Data frame.  That will give an error, because it only copies if the existing data frame is the same length, or a multiple of the length of the data you are copying.

@rachelkg I hope this answers your questions.  Otherwise maybe Fidel can test and help more?

**Comment by rachelkg** [comment] 2024-02-15 18:39
@rdstern thank you for the clarification. The last thing I need to move forward with the help is an example of a dataset that I could use to show how/when this works well. 

The length issue must be what I was coming up against when I was trying to use the Column option. I will try some with a matching length. 

Best, Rachel

**Comment by rachelkg** [comment] 2024-02-15 22:35
I have decided to use a table from here https://worldpopulationreview.com/country-rankings/greenhouse-gas-emissions-by-country. 

I tried to use a table that matched in length from here https://worldpopulationreview.com/country-rankings/carbon-footprint-by-country.

I wonder if i am missing something or if there is a program error.  Could someone else try and see what they find?

This is the error i get: 
![2024-02-15_13-44-29](https://github.com/IDEMSInternational/R-Instat/assets/85707390/860ac989-a359-4b35-9a6e-352085b2694a)

**Comment by rdstern** [comment] 2024-02-15 23:27
@rachelkg when I go there I just get a picture with repeated advertising:

![image](https://github.com/IDEMSInternational/R-Instat/assets/11226469/b8f4a0cb-1866-4fc2-a2ed-7472ad8410f8)

I am not sure how to get to the data.

**Comment by rachelkg** [comment] 2024-04-09 21:54
@rdstern I think you just need to scroll down to find the data. It is below the ad. 

But I have I have found a better example which doesn't have any advertising on the page and has both data sets on the same page https://www.ucsusa.org/resources/each-countrys-share-co2-emissions. 

With this I thought It would be nice to use the information from the first table which has 15 rows, then to copy the first 15 rows of the second table and try to add them to the first data frame. 
I add the first set no problem using paste new dataframe
![2024-04-09_14-51-20](https://github.com/IDEMSInternational/R-Instat/assets/85707390/5a490704-8d78-4357-8254-7bce9b0f5522)
![2024-04-09_14-51-50](https://github.com/IDEMSInternational/R-Instat/assets/85707390/111c6ddd-9048-48ee-9a48-fd6179ed32d6)
But when I try to add this using the Columns option I get the same error message as above. 
![2024-04-09_14-51-31](https://github.com/IDEMSInternational/R-Instat/assets/85707390/4d163fac-3c8e-48f1-a94b-3a7671ae75e4)
![2024-04-09_14-51-58](https://github.com/IDEMSInternational/R-Instat/assets/85707390/5e7a8a4d-9a0b-488f-8c5b-f69b7c5ebc8f)
![2024-04-09_14-46-08](https://github.com/IDEMSInternational/R-Instat/assets/85707390/0d4ff026-fcf3-456f-b118-4da343467bbe)

It works fine to make a new data frame from the data in the click board but the columns tab is not working for me. Can someone else try it?

**Comment by Patowhiz** [comment] 2024-04-22 10:30
@rachelkg @Fidel365 @rdstern

We labelled the menu item as "Paste New" because the dialog performs two main functions:
- Pasting a new data frame.
- Pasting new columns into an existing data frame.

The maximum length of data allowed is 1000 rows. When pasting new columns, the length of the data should match the data frame into which you are pasting.

@Fidel365, I noticed you changed the menu label. @rdstern, I suggest we revert these changes.

@rachelkg, thank you for spotting the error thrown when pasting new columns into an existing data frame.

@N-thony, the error thrown when pasting new columns is due to a regression introduced in the `data_book$add_columns_to_data()` function within the R file `data_object_R6.R`. This function throws an error when attempting to add multiple columns, particularly noted in line 683. Recent additions/changes seem to be causing this issue. Please review and adjust the function accordingly.

For debugging, @N-thony, you can use the following R commands:

**Import a new data frame from a the paste dialog command**
```
data <- clipr::read_clip_tbl(x = "Rank	Country	CO2 emissions (total)
1	United States	421,907MT
2	China	249,353MT
3	Russia	117,548MT
4	Germany	93,291MT", header = TRUE)
data_book$import_data(data_tables = list(data = data))
```
**Attempt to paste multiple columns (currently not working)**
```
two_cols_data <- clipr::read_clip_tbl(x = "1	United States
2	China
3	Russia
4	Germany", header = FALSE)
data_book$add_columns_to_data(data_name = "data", col_data = two_cols_data, use_col_name_as_prefix = TRUE)
```

**Pasting a single column (works fine)**
```
single_col_data <- clipr::read_clip_tbl(x = "1
2
3
4", header = FALSE)
data_book$add_columns_to_data(data_name = "data", col_data = single_col_data, use_col_name_as_prefix = TRUE)
```

**Closed** 2024-05-15 13:04 UTC
